### PR TITLE
Add Random Pkg to Project toml

### PR DESCRIPTION
**Pull request by lrennels**
@jrising I think if we add `Random` to the Project.toml and then tag this should all be running smoothly but double check me on that. Sorry I should've done this from a branch on my fork, happy to do so if you prefer.

### CODE REVIEW

**Comment by jrising** [comment]
Yup, we definitely need this. Thanks!

**Comment by jrising** [comment]
@lrennels What's the right way to get the package updated in the Julia package repository? The instructions I found seem significantly changed since the last time I did this, and I'm not sure if they'll work for a non-new package.

**Comment by lrennels** [comment]
@jrising good question, the way I've actually done it recently has been to use the VSCode extension action that David A added, it's in Beta but works well for me, and if there are any snafoos I can help fix them because I've had them too, do you us VSCode?

**Comment by jrising** [comment]
@lrennels I haven't used VSCode for many years. Okay, I'll hope the new TagBot process works as expected.

**Pull request merged**
